version: '3'

services:
  client:
    build:
      context: ./front-end/javascript/react/apollo-client/v2.6.x/apollo-tutorial
      dockerfile: ./Dockerfile
    container_name: 'apollo-tutorial-app'
    command: ./node_modules/.bin/react-scripts start
    ports:
      - "3000:3000"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./front-end/javascript/react/apollo-client/v2.6.x/apollo-tutorial/src:/app/src
    depends_on:
      - server

  server:
    build:
      context: ./back-end/javascript/apollo-server/apollo-tutorial
      dockerfile: ./Dockerfile
    container_name: 'apollo-tutorial-server'
    # Automatically hot reload code changes in the Docker container
    command: sh -c 'npx nodemon -e js,json,graphql'
    ports:
      - "4000:4000"
      - "9229:9229"
