version: '3'

services:
  client:
    build:
      context: ../../front-end/javascript/react/apollo-client/v2.6.x/apollo-tutorial
      dockerfile: ./Dockerfile
    container_name: 'explore-graphql-app'
    command: ./node_modules/.bin/react-scripts start
    ports:
      - "3000:3000"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ../../front-end/javascript/react/apollo-client/v2.6.x/apollo-tutorial/src:/app/src
    depends_on:
      - server

  server:
    build:
      context: ../../back-end/javascript/apollo-server/apollo-tutorial
      dockerfile: ./Dockerfile
    container_name: 'explore-graphql-server'
    # This service will not start until either the mongodb service is available OR thirty seconds have elapsed
    command: sh -c './scripts/wait-for.sh --timeout=30 postgres:5432 && npx nodemon -e js,json,graphql'
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - postgres

  # Use the pre-defined PostgreSQL image
  postgres:
    image: postgres:9.6
    container_name: 'explore-graphql-postgresql'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    # If you want to persist data after a container has been stopped/deleted, uncomment the volumes section
    # volumes:
    #   - ./databases/postgresql/sandbox/data:/var/lib/postgresql/data
