version: '3'

services:
  apollo-tutorial-angular:
    build:
      context: ../../front-end/javascript/angular/apollo-client/apollo-tutorial
      dockerfile: ./Dockerfile
    container_name: 'apollo-tutorial-angular'
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
      - "9876:9876"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ../../front-end/javascript/angular/apollo-client/apollo-tutorial:/app
      - ../../front-end/javascript/angular/apollo-client/apollo-tutorial/src:/app/src
      # Use the node_modules folder within our Docker container and NOT the local development environment folder
      - /app/node_modules
